export const WAVE_PRESETS = {
	bloom: {
		audioScale: 1,
		uWhiteClip: 1,
		uUnresolvedScale: 0.14,
		uAmplitude: 0.22,
		uFreq: 1.1,
		uAberrationFreq: 1,
		uWaveSpeed: -1,
		uWaveScale: 0.9,
		uAberration: 2.6,
		uThickness: 3,
		uIntensity: 2,
		uFalloff: 1.7,
		uEdgeMask: 0.4,
		uEdgeMaskInset: 0,
		uBandFill: 30000,
		uBandFillThickness: 0.08,
		uSoftness: 2.5,
		uLowAmplitude: 6,
		uLowIntensity: 1.5,
		uMidAberration: 0.8,
		uMidAberrationAmplitude: 0.05,
		uMidBandFill: 0,
		uMidSoftness: 0.4,
		uHighAberration: 0.5,
		uHighAberrationAmplitude: 0.06,
	}
};
